import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { Nav, NavLink } from '@/components/Nav';
import prisma from '@/prisma/prismaDb';
import Link from 'next/link';
import SignInAndOutButtons from '@/components/SignInAndOutButton';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await prisma.category.findMany();
  return (
    <html lang="en">
      <body
        className={cn(
          'bg-background min-h-screen font-sans antialiased',
          inter.variable
        )}
      >
        <header className="bg-primary">
          <nav className="flex justify-between items-center px-4 py-8">
            <Link
              href="/"
              className="inline-block leading-5 text-xl pr-4 text-slate-50 font-thin border-r-2 border-indigo-600"
            >
              my
              <br />
              <span className="font-normal">blog</span>
            </Link>
            <Nav>
              {categories.map((category) => (
                <NavLink
                  key={category.id}
                  href={`/${encodeURIComponent(category.slug)}`}
                >
                  <span className="capitalize">{category.name}</span>
                </NavLink>
              ))}
              <SignInAndOutButtons />
            </Nav>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
